name: Deploy Next.js App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Match your local version

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run tests (optional)
      run: npm test

    - name: Export static site (optional for static export only)
      run: npm run export

    # Example: Upload build artifacts (optional)
    - name: Upload production build
      uses: actions/upload-artifact@v3
      with:
        name: nextjs-build
        path: .next

    # You can add deploy steps below (e.g. Vercel, FTP, SSH, Docker, etc.)
